# Full configuration options can be found at https://www.vaultproject.io/docs/configuration

ui = true

#mlock = true
#disable_mlock = true

storage "raft" {
  path = "/opt/vault/data"


  # The retry_join bit will be generated by terraform on the fly
  # once we know who our cluster peers are.
  retry_join {
      auto_join = "provider=aws region=##REGION_HERE## tag_key=##TAG_HERE## tag_value=server"
      auto_join_scheme = "http"
      addr_type = "private_v4"
  }
}

cluster_addr = "http://##CLUSTER_ADDR_HERE##:8201"
api_addr = "http://##API_ADDR_HERE##:8200"




# HTTP listener
#listener "tcp" {
#  address = "172.27.198.189:8200"
#  tls_disable = 1
#}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

# HTTPS listener
#listener "tcp" {
#  address       = "0.0.0.0:8200"
#  tls_cert_file = "/opt/vault/tls/vault.crt"
#  tls_key_file  = "/opt/vault/tls/vault.key"
#}

# Enterprise license_path
# This will be required for enterprise as of v1.8
license_path = "/etc/vault.d/license.hclic"

# Example AWS KMS auto unseal
#seal "awskms" {
#  region = "us-east-1"
#  kms_key_id = "REPLACE-ME"
#}

# Example HSM auto unseal
#seal "pkcs11" {
#  lib            = "/usr/vault/lib/libCryptoki2_64.so"
#  slot           = "0"
#  pin            = "AAAA-BBBB-CCCC-DDDD"
#  key_label      = "vault-hsm-key"
#  hmac_key_label = "vault-hsm-hmac-key"
#}
